version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: pgdev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: